name: check template
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./script/konstraint.sh create . -o k8s
          git diff --quiet
