name: check template
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSLo konstraint https://github.com/plexsystems/konstraint/releases/download/v0.24.0/konstraint-linux-amd64
          chmod +x konstraint
          ./konstraint create . -o k8s
          git diff --quiet
