name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  opa:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: opa test .
  conftest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: conftest verify
