name: comment-coverage
on:
  pull_request:
    branches:
      - master
jobs:
  comment-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: open-policy-agent/setup-opa@v2
      - name: Export coverage
        run: |
          echo "COVERAGE=$(opa test policy -c | jq .coverage)" >> $GITHUB_ENV
      - name: Format comment
        run: |
          echo "coverage: ${{ env.COVERAGE }}%" >> comment
      - name: Comment coverage to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment -F ./comment "${URL}"