name: comment-coverage
on:
  pull_request:
    branches:
      - master
jobs:
  comment-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v2
      - run: |
          echo "COVERAGE=$(opa test policy -c | jq .coverage)%" >> $GITHUB_ENV
      - run: |
          echo "coverage: ${{ env.COVERAGE }}%" >> comment
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment -F ./comment "${URL}"
