name: conftest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  conftest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.25.0
      - run: |
          conftest test example/safe.yaml
          ! conftest test example/unsafe.yaml # should fail
          conftest test example/allowed.yaml
