name: coverage-badge
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: open-policy-agent/setup-opa@v2
      - name: Export coverage
        run: echo "COVERAGE=$(opa test policy -c | jq .coverage)" >> $GITHUB_ENV
      - name: Calc color
        run: |
          coverage=${{ env.COVERAGE }}
          min=50
          max=90
          rounded=$((90 < test ? 90 : test < 50 ? 50 : test))
          hue=$(((rounded - min) * 120/ (max - min)))
          echo "COLOR=hsl($hue, 100%, 40%)" >> $GITHUB_ENV
      - name: Upload JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_SECRET }}
        run: |
          echo '{"schemaVersion":1,"label":"Coverage","message":"${{ env.COVERAGE }}%","color":"${{ env.COLOR }}"}' >> test.json
          gh gist edit 6641f83484aca3643c1f6d9ddee38260 test.json
