name: coverage
on:
  pull_request:
    branches:
      - master
jobs:
  comment-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v2
      - run: opa test policy -c > result.json
      - run: |
          echo "coverage: $(cat result.json | jq .coverage)%" >> comment
          cat <<EOF >> comment
          <details>
            <summary>
              details
            </summary>

            \`\`\`json
            $(cat result.json)
            \`\`\`

            </div>
          </details>
          EOF
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comment "${URL}"
